# Generated by Django 3.0.8 on 2020-11-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pictures/default.jpg', upload_to='media/profile_pictures'),
        ),
    ]
